### ISSUE TITLE
Discord側のVoiceAPIの仕様変更による読み上げ不良

### ISSUE THREAD

**Issue by AI-Avalon** [Ebycow/hanako#47]
`[2023-03-22T19:02:52.200] [ERROR] application.js - 予期しないエラーが発生。 Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (C:\Users\USER\Documents\DocmentsAvalon\VoiceroidBot\hanako\node_modules\discord.js\src\client\voice\VoiceConnection.js:304:26)
    at C:\Users\USER\Documents\DocmentsAvalon\VoiceroidBot\hanako\node_modules\discord.js\src\client\voice\VoiceConnection.js:325:61
    at Timeout.<anonymous> (C:\Users\USER\Documents\DocmentsAvalon\VoiceroidBot\hanako\node_modules\discord.js\src\client\BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  [Symbol(code)]: 'VOICE_CONNECTION_TIMEOUT'
}`
上記のようなエラーで、読み上げが不可能になってしまっています。
もし可能でしたら修正していただけると嬉しいです。

**Comment by Ebycow** [comment]
Masterブランチを使用している場合，可及的な対応ですが"slashbros"ブランチ https://github.com/Ebycow/hanako/commit/6f214f93cd57969fb97183d50869f295601a2795 を利用して動くかチェックしてみて下さい．この時Discord Developer Portal側でMESSAGE CONTENT INTENTの有効化が必要になるかもしれません

**Comment by Ebycow** [comment]
動作確認は16.16.0を使用しています
https://nodejs.org/en/blog/release/v16.16.0

**Comment by Ebycow** [comment]
package.jsonを変更しnode-libsamplerateの依存関係をローカルに保存したものに変更していた事を忘れていました，すいません

cmakeをインストールした状態で，hanakoと同じ階層のディレクトリにnode-libsamplerateをクローンします
`git clone https://github.com/nanokina/node-libsamplerate.git`

その後，node-libsamplerateディレクトリに移動し，`git submodule update --init --recursive` でサブモジュールをプルします
次に，node-libsamplerateディレクトリで `npm i` でビルドを行います．

完了後にhanakoディレクトリに移動し，hanakoを `npm i` でインストールします．

すいませんが，私はまだsubmoduleの解決方法が分からないので，当面はこのようにしてお願いします…

**Comment by AI-Avalon** [comment]
ありがとうございます
上記のアドバイス通りに実行した結果しっかり読みあげてくれるようになりました！
本当にありがとうございました。
